FROM python:3.10-slim-bullseye

COPY ./src/ /app/
COPY ./requirements.txt /app/

WORKDIR "/app"

RUN pip install -r requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/app/"
EXPOSE 8080

CMD ["python", "/app/flaskr/main.py"]